### ISSUE TITLE
coolapk动态评论区

### ISSUE THREAD

**Issue by laishouchao** [lsc183754539/lsc183754539.github.io#3]
# 嘿;-) talk with us！

**Comment by laishouchao** [comment]
# 各位基佬们好！在这里我们可以继续开车！😏😏😏  
![8BzdP0.jpg](https://s1.ax1x.com/2020/03/18/8BzdP0.jpg)

**Comment by AferCarmichael** [comment]
来了

**Comment by lsc183754539** [comment]
> ·

嘿嘿嘿

**Comment by chainsx** [comment]
所以说，316到底是什么事，有截图什么的没有

**Comment by JiYeHuanXing** [comment]
看我发现了什么

**Comment by lsc183754539** [comment]
> 所以说，316到底是什么事，有截图什么的没有

有的  
![316经过](https://s1.ax1x.com/2020/03/19/8Dj9YV.png)

**Comment by lsc183754539** [comment]
> 看我发现了什么

发现了新世界，哈哈哈哈

**Comment by chainsx** [comment]
> > 所以说，316到底是什么事，有截图什么的没有
> 
> 有的
> ![316经过](https://camo.githubusercontent.com/2e311795382b4184350853ba5171225247b69583/68747470733a2f2f73312e617831782e636f6d2f323032302f30332f31392f38446a3959562e706e67)

我知道这个，我是想知道，到底是涉政还是涉黄还是涉恐？
